### ISSUE TITLE
problem recognizing Symbol type

### ISSUE THREAD

**Issue by xiazek** [mame/typeprof-playground#6]
## Issue

`sex: :male` should result in Symbol type.

## ruby
```ruby
# test.rb
class User
  def initialize(sex:, age:)
    @sex, @age = sex, age
  end
  
  attr_reader :sex, :age
end

User.new(sex: :male, age: 20)
```
## rbs
```ruby

```
## output
```
# Classes
class User
  def initialize: (sex: :male, age: Integer) -> [:male, Integer]
  attr_reader sex: :male
  attr_reader age: Integer
end


## Version info:
##   * Ruby: 3.0.0
##   * RBS: 1.0.0
##   * TypeProf: 0.11.0

```

**Comment by mame** [comment]
Sorry, I missed this report!

Do you mean you expect `attr_reader sex: Symbol` instead of `attr_reader sex: :male`?
This result is by design because a Symbol is often used as a concrete value, such as a label.
If we regard all symbols as one Symbol object, it would be difficult to handle JSON-like data.

```
h = {}
h[:name] = "John"
h[:age] = 42
p h #=> current: {name: String, age: Integer}
    #   changed: {Symbol=>String | Integer}
```

I come up with three solutions.

1. Add a test case if you expect a fixed set of values for the `sex` field.
For example, by feeding the following test, TypeProf will produce `attr_reader sex: :male | :female`.
 
```
User.new(sex: :male, age: 20)
User.new(sex: :female, age: 20)
```

2. Use String instead of Symbol if the set of values is not fixed.
IMO, it is recommended to use Symbols only if the candidates are fixed.
The following test will produce `attr_reader sex: String`.

```
User.new(sex: "male", age: 20)
```

3. If you really want TypeProf to show `Symbol` instead of `:male`, use `"male".to_sym`.
`String#to_sym` returns an abstract `Symbol` type because TypeProf does not keep the concrete content of `String`.
For example, the following test will produce `attr_reader sex: Symbol`.

```
User.new(sex: "male".to_sym, age: 20)
```

Thank you for your trying TypeProf and giving me a feedback!

**Comment by xiazek** [comment]
Thanks @mame ! 
I've assumed this was a bug initially... but knowing the behaviour and assumptions behind, this is actually really fantastic. 
I especially like the `1.` with kind of "enum" definition as a result. 

Thank you very much !
